env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - eslint-plugin-prettier
rules:
  react/prop-types: off
  prettier/prettier:
    - error
  react/jsx-filename-extension:
    - 2
    - extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
  devDependencies: true
  '@typescript-eslint/naming-convention':
    - error
    - selector: interface
      format:
        - PascalCase
      custom:
        regex: '^I[A-Z]'
        match: false
settings:
  import/resolver: webpack
