env:
  browser: true
  es2021: true
extends:
  - airbnb
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/prop-types: off
  react/jsx-filename-extension:
    - 2
    - extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
  devDependencies: 0
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/no-extraneous-dependencies:
    - error
    - devDependencies: false
      optionalDependencies: false
  no-use-before-define: off
  import/order:
    - warn
    - alphabetize:
        order: asc
      newlines-between: always
  no-shadow: off
  "@typescript-eslint/no-shadow":
    - error
  import/no-unresolved: error
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: tsconfig.json,
  import/core-modules:
  - electron
overrides:
  - files:
    - "./**/*.ts"
    excludedFiles:
    - "./**/*.spec.ts"
